<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="0" name="NUnitTestProj.dll" fullname="C:\dev\Playground\NUnit\bin\Debug\net9.0\NUnitTestProj.dll" runstate="Runnable" testcasecount="4" result="Failed" total="4" passed="1" failed="2" warnings="0" inconclusive="0" skipped="1" asserts="2" engine-version="3.18.1.0" clr-version="9.0.0" start-time="2024-11-20 10:15:12Z" end-time="2024-11-20 10:15:12Z" duration="0.062075">
  <command-line><![CDATA[C:\dev\Playground\NUnit\bin\Debug\net9.0\testhost.dll --port 52057 --endpoint 127.0.0.1:052057 --role client --parentprocessid 2856 --telemetryoptedin false]]></command-line>
  <test-suite type="Assembly" id="0-1005" name="NUnitTestProj.dll" fullname="C:\dev\Playground\NUnit\bin\Debug\net9.0\NUnitTestProj.dll" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2024-11-20T10:15:12.7307782Z" end-time="2024-11-20T10:15:12.7774522Z" duration="0.046649" total="4" passed="1" failed="2" warnings="0" inconclusive="0" skipped="1" asserts="2">
    <environment framework-version="4.2.2.0" clr-version="9.0.0" os-version="Microsoft Windows 10.0.19045" platform="Win32NT" cwd="C:\dev\Playground\NUnit\bin\Debug\net9.0" machine-name="PC-L0109" user="alexander.meseldzija" user-domain="PC-L0109" culture="en-AU" uiculture="en-GB" os-architecture="x64" />
    <settings>
      <setting name="SynchronousEvents" value="False" />
      <setting name="InternalTraceLevel" value="Off" />
      <setting name="RandomSeed" value="501998260" />
      <setting name="SkipNonTestAssemblies" value="True" />
      <setting name="ProcessModel" value="InProcess" />
      <setting name="DomainUsage" value="Single" />
      <setting name="DefaultTestNamePattern" value="{m}{a}" />
      <setting name="WorkDirectory" value="C:\dev\Playground\NUnit\bin\Debug\net9.0" />
      <setting name="NumberOfTestWorkers" value="16" />
    </settings>
    <properties>
      <property name="_PID" value="57560" />
      <property name="_APPDOMAIN" value="testhost" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1006" name="NUnitTestProject" fullname="NUnitTestProject" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2024-11-20T10:15:12.7342887Z" end-time="2024-11-20T10:15:12.7774196Z" duration="0.043131" total="4" passed="1" failed="2" warnings="0" inconclusive="0" skipped="1" asserts="2">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="UnitTest1" fullname="NUnitTestProject.UnitTest1" classname="NUnitTestProject.UnitTest1" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2024-11-20T10:15:12.7350880Z" end-time="2024-11-20T10:15:12.7770812Z" duration="0.041994" total="4" passed="1" failed="2" warnings="0" inconclusive="0" skipped="1" asserts="2">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="0-1001" name="NUnitTestMethod1" fullname="NUnitTestProject.UnitTest1.NUnitTestMethod1" methodname="NUnitTestMethod1" classname="NUnitTestProject.UnitTest1" runstate="Runnable" seed="477349529" result="Passed" start-time="2024-11-20T10:15:12.7368699Z" end-time="2024-11-20T10:15:12.7450597Z" duration="0.008230" asserts="1" />
        <test-case id="0-1004" name="NUnitTestShouldError" fullname="NUnitTestProject.UnitTest1.NUnitTestShouldError" methodname="NUnitTestShouldError" classname="NUnitTestProject.UnitTest1" runstate="Runnable" seed="393620580" result="Failed" label="Error" start-time="2024-11-20T10:15:12.7459177Z" end-time="2024-11-20T10:15:12.7520320Z" duration="0.006114" asserts="0">
          <failure>
            <message><![CDATA[System.Exception : This is an error]]></message>
            <stack-trace><![CDATA[   at NUnitTestProject.UnitTest1.NUnitTestShouldError() in C:\dev\Playground\NUnit\UnitTest1.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)]]></stack-trace>
          </failure>
        </test-case>
        <test-case id="0-1002" name="NUnitTestShouldFail" fullname="NUnitTestProject.UnitTest1.NUnitTestShouldFail" methodname="NUnitTestShouldFail" classname="NUnitTestProject.UnitTest1" runstate="Runnable" seed="1704830536" result="Failed" label="HelloThere" start-time="2024-11-20T10:15:12.7521135Z" end-time="2024-11-20T10:15:12.7754970Z" duration="0.023384" asserts="1">
          <failure>
            <message><![CDATA[  Assert.That(false, Is.True)
  Expected: True
  But was:  False
]]></message>
            <stack-trace><![CDATA[   at NUnitTestProject.UnitTest1.NUnitTestShouldFail() in C:\dev\Playground\NUnit\UnitTest1.cs:line 15
]]></stack-trace>
          </failure>
          <assertions>
            <assertion result="Failed">
              <message><![CDATA[  Assert.That(false, Is.True)
  Expected: True
  But was:  False
]]></message>
              <stack-trace><![CDATA[   at NUnitTestProject.UnitTest1.NUnitTestShouldFail() in C:\dev\Playground\NUnit\UnitTest1.cs:line 15
]]></stack-trace>
            </assertion>
          </assertions>
        </test-case>
        <test-case id="0-1003" name="NUnitTestShouldSkip" fullname="NUnitTestProject.UnitTest1.NUnitTestShouldSkip" methodname="NUnitTestShouldSkip" classname="NUnitTestProject.UnitTest1" runstate="Ignored" seed="2144882532" result="Skipped" label="Ignored" start-time="2024-11-20T10:15:12.7755442Z" end-time="2024-11-20T10:15:12.7758202Z" duration="0.000276" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="I said so" />
          </properties>
          <reason>
            <message><![CDATA[I said so]]></message>
          </reason>
        </test-case>
      </test-suite>
    </test-suite>
  </test-suite>
    <test-suite type="Assembly" id="1036" name="mock-assembly.dll" fullname="D:\Dev\NUnit\nunit-3.0\work\bin\vs2008\Debug\mock-assembly.dll" testcasecount="25" result="Failed" time="0.154" total="18" passed="12" failed="2" inconclusive="1" skipped="3" asserts="2">
    <properties>
      <property name="_PID" value="11928" />
      <property name="_APPDOMAIN" value="test-domain-mock-assembly.dll" />
    </properties>
    <failure>
      <message><![CDATA[Child test failed]]></message>
    </failure>
    <test-suite type="TestFixture" id="1000" name="MockTestFixture" fullname="NUnit.Tests.Assemblies.MockTestFixture" testcasecount="11" result="Failed" time="0.119" total="10" passed="4" failed="2" inconclusive="1" skipped="3" asserts="0">
      <properties>
        <property name="Category" value="FixtureCategory" />
        <property name="Description" value="Fake Test Fixture" />
      </properties>
      <failure>
        <message><![CDATA[Child test failed]]></message>
      </failure>
      <test-case id="1005" name="FailingTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.FailingTest" result="Failed" time="0.023" asserts="0">
        <failure>
          <message><![CDATA[Intentional failure]]></message>
          <stack-trace><![CDATA[   at NUnit.Framework.Assert.Fail(String message, Object[] args) in D:\Dev\NUnit\nunit-3.0\work\NUnitFramework\src\framework\Assert.cs:line 142
   at NUnit.Framework.Assert.Fail(String message) in D:\Dev\NUnit\nunit-3.0\work\NUnitFramework\src\framework\Assert.cs:line 152
   at NUnit.Tests.Assemblies.MockTestFixture.FailingTest() in D:\Dev\NUnit\nunit-3.0\work\NUnitFramework\src\mock-assembly\MockAssembly.cs:line 121]]></stack-trace>
        </failure>
      </test-case>
      <test-case id="1010" name="InconclusiveTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.InconclusiveTest" result="Inconclusive" time="0.001" asserts="0" />
      <test-case id="1001" name="MockTest1" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest1" result="Passed" time="0.000" asserts="0">
        <properties>
          <property name="Description" value="Mock Test #1" />
        </properties>
      </test-case>
      <test-case id="1002" name="MockTest2" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest2" result="Passed" time="0.000" asserts="0">
        <properties>
          <property name="Severity" value="Critical" />
          <property name="Description" value="This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really long description" />
          <property name="Category" value="MockCategory" />
        </properties>
      </test-case>
      <test-case id="1003" name="MockTest3" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest3" result="Passed" time="0.000" asserts="0">
        <properties>
          <property name="Category" value="AnotherCategory" />
          <property name="Category" value="MockCategory" />
        </properties>
      </test-case>
      <test-case id="1007" name="MockTest4" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest4" result="Skipped" label="Ignored" time="0.000" asserts="0">
        <properties>
          <property name="Category" value="Foo" />
          <property name="_SKIPREASON" value="ignoring this test method for now" />
        </properties>
        <reason>
          <message><![CDATA[ignoring this test method for now]]></message>
        </reason>
      </test-case>
      <test-case id="1004" name="MockTest5" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest5" result="Skipped" label="Invalid" time="0.000" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="Method is not public" />
        </properties>
        <reason>
          <message><![CDATA[Method is not public]]></message>
        </reason>
      </test-case>
      <test-case id="1009" name="NotRunnableTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest" result="Skipped" label="Invalid" time="0.000" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="No arguments were provided" />
        </properties>
        <reason>
          <message><![CDATA[No arguments were provided]]></message>
        </reason>
      </test-case>
      <test-case id="1011" name="TestWithException" fullname="NUnit.Tests.Assemblies.MockTestFixture.TestWithException" result="Failed" label="Error" time="0.002" asserts="0">
        <failure>
          <message><![CDATA[System.ApplicationException : Intentional Exception]]></message>
          <stack-trace><![CDATA[   at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException() in D:\Dev\NUnit\nunit-3.0\work\NUnitFramework\src\mock-assembly\MockAssembly.cs:line 158
   at NUnit.Tests.Assemblies.MockTestFixture.TestWithException() in D:\Dev\NUnit\nunit-3.0\work\NUnitFramework\src\mock-assembly\MockAssembly.cs:line 153]]></stack-trace>
        </failure>
      </test-case>
      <test-case id="1006" name="TestWithManyProperties" fullname="NUnit.Tests.Assemblies.MockTestFixture.TestWithManyProperties" result="Passed" time="0.000" asserts="0">
        <properties>
          <property name="TargetMethod" value="SomeClassName" />
          <property name="Size" value="5" />
        </properties>
      </test-case>
    </test-suite>
    <test-suite type="TestFixture" id="1023" name="BadFixture" fullname="NUnit.Tests.BadFixture" testcasecount="1" result="Skipped" label="Invalid" time="0.000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
      <properties>
        <property name="_SKIPREASON" value="No suitable constructor was found" />
      </properties>
      <reason>
        <message><![CDATA[No suitable constructor was found]]></message>
      </reason>
    </test-suite>
    <test-suite type="TestFixture" id="1025" name="FixtureWithTestCases" fullname="NUnit.Tests.FixtureWithTestCases" testcasecount="2" result="Passed" time="0.010" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
      <test-suite type="ParameterizedMethod" id="1026" name="MethodWithParameters" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters" testcasecount="2" result="Passed" time="0.009" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
        <test-case id="1027" name="MethodWithParameters(2,2)" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters(2,2)" result="Passed" time="0.006" asserts="1" />
        <test-case id="1028" name="MethodWithParameters(9,11)" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters(9,11)" result="Passed" time="0.000" asserts="1" />
      </test-suite>
    </test-suite>
    <test-suite type="TestFixture" id="1016" name="IgnoredFixture" fullname="NUnit.Tests.IgnoredFixture" testcasecount="3" result="Skipped" label="Ignored" time="0.000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
      <properties>
        <property name="_SKIPREASON" value="" />
      </properties>
      <reason>
        <message><![CDATA[]]></message>
      </reason>
    </test-suite>
    <test-suite type="ParameterizedFixture" id="1029" name="ParameterizedFixture" fullname="NUnit.Tests.ParameterizedFixture" testcasecount="4" result="Passed" time="0.007" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="0">
      <test-suite type="TestFixture" id="1030" name="ParameterizedFixture(42)" fullname="NUnit.Tests.ParameterizedFixture(42)" testcasecount="2" result="Passed" time="0.003" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <test-case id="1031" name="Test1" fullname="NUnit.Tests.ParameterizedFixture(42).Test1" result="Passed" time="0.000" asserts="0" />
        <test-case id="1032" name="Test2" fullname="NUnit.Tests.ParameterizedFixture(42).Test2" result="Passed" time="0.000" asserts="0" />
      </test-suite>
      <test-suite type="TestFixture" id="1033" name="ParameterizedFixture(5)" fullname="NUnit.Tests.ParameterizedFixture(5)" testcasecount="2" result="Passed" time="0.002" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <test-case id="1034" name="Test1" fullname="NUnit.Tests.ParameterizedFixture(5).Test1" result="Passed" time="0.000" asserts="0" />
        <test-case id="1035" name="Test2" fullname="NUnit.Tests.ParameterizedFixture(5).Test2" result="Passed" time="0.000" asserts="0" />
      </test-suite>
    </test-suite>
    <test-suite type="TestFixture" id="1012" name="OneTestCase" fullname="NUnit.Tests.Singletons.OneTestCase" testcasecount="1" result="Passed" time="0.001" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
      <test-case id="1013" name="TestCase" fullname="NUnit.Tests.Singletons.OneTestCase.TestCase" result="Passed" time="0.000" asserts="0" />
    </test-suite>
    <test-suite type="TestFixture" id="1014" name="MockTestFixture" fullname="NUnit.Tests.TestAssembly.MockTestFixture" testcasecount="1" result="Passed" time="0.001" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
      <test-case id="1015" name="MyTest" fullname="NUnit.Tests.TestAssembly.MockTestFixture.MyTest" result="Passed" time="0.001" asserts="0" />
    </test-suite>
  </test-suite>
</test-run>